### ISSUE TITLE
strange behavior on display drawing

### ISSUE THREAD

**Issue by eugeniobaglieri** [uraimo/5110LCD_PCD8544.swift#1]
Watch the attached gif, is that normal that i can see image being drawn block by block?
This is my code

``` swift
let gpios = SwiftyGPIO.getGPIOsForBoard(.RaspberryPiPlus2Zero)

var clk = gpios[.P17]!
var din = gpios[.P18]!
var dc = gpios[.P27]!
var cs = gpios[.P22]!
var rst = gpios[.P23]!


var spi = VirtualSPI(dataGPIO: din, clockGPIO: clk)

var lcd = PCD8544(spi: spi, dc: dc, rst: rst, cs: cs)
lcd.clearDisplay()
lcd.display()

lcd.drawImage(swift_logo,x:0,y:0,width:LCDWIDTH,height:LCDHEIGHT,transparent:true)
lcd.display()
```

![lcd](https://cloud.githubusercontent.com/assets/1050414/13018838/472ed822-d1cc-11e5-8cde-8375b8782df5.gif)

**Comment by uraimo** [comment]
Sadly it's normal, the bit banging SPI of SwiftyGPIO is extremely slow since the library writes one byte at a time (a 8rows x 1column pixel block from the top-left, after the byte is written it sends a clock impulse). Considering it's done via sysFS, it does a total of 3 open/write/close for each 8x1 element.

When i implemented it i tried keeping the gpio file descriptor open to speed things up,  but the speedup (50% i'd say, when we'll need at least 5-fold speedup) was not worth the increase in complexity of the code. I could reconsider, btw.

I guess you've already read this, but what you can do since you are using a Raspi is to enable the hardware SPI as described [here](https://github.com/uraimo/SwiftyGPIO/wiki/Enabling-SPI-on-RaspberryPi-and-others), move your connectors and modify your code like this:

``` swift
let spis = SwiftyGPIO.getHardwareSPIsForBoard(.RaspberryPiPlus2Zero)
var spi = spis?[0]
```

**Comment by eugeniobaglieri** [comment]
i'm using this preassembled board, so changing wirings is not easy :)
![61ev-xabpil _sl1000_](https://cloud.githubusercontent.com/assets/1050414/13019782/b4909b62-d1d1-11e5-9691-6a82cd602cbf.jpg)

I read all the SwiftyGPIO code, i think that a solution could be something like enable an optional enabled 1byte "buffer" for each GPIO pin, when this buffer became full, write all the buffer to the file in a single operation. In this way it does 1 file open, one byte block write, and 1 file close. What do you think? i saw that clk doesn't have a real timing.

**Comment by uraimo** [comment]
The SPI pins are described [here](https://www.raspberrypi.org/documentation/hardware/raspberrypi/spi/README.md):

```
MOSI    P1-19
MISO    P1-21
SCLK    P1-23
CE-0     P1-24
GND     P1-25
CE-1     P1-26
```

In your case, once you enable the SPI you will not be able to use the pins above as you used to since they will change their function, you'll need to place at least P22 and P23 somewhere else.

Regarding the rest, you used P17 as clock and P17 as din/mosi, the clock will now be on P23 and the mosi on P19.

Moving those should be enough.

**Comment by uraimo** [comment]
Ouch! Yes, the clock at the moment just sends an impulse with no particular timing since everything else is so incredibly slow.

The code you see now is the result of the fact that the virtual spi object is based on the gpio object, that can only send a single Int (either 0 or 1) and while i like the fact that the init() makes clear that we are creating a new SPI object _composed by_ two gpios, this limits a lot what the spi can do (even sending an array of UInt8 instead of a single byte was added lately).

Sending everything without all those open/closes, even all the data not just one bit, would improve a bit, but we can't just write all the array of bytes since we must still perform a clock transition **for every bit, or the lcd will not read the value.**

So, the best way to do it is to reimplement the write method directly into VirtualSPI.sendData and stop using gpio.value, we'll have a bit of code duplication but since we need to write on both MOSI and CLK every iteration that's the only way.

I'll take a look at it tomorrow.

**Comment by eugeniobaglieri** [comment]
Using your suggestion of keep file pointers open i obtained a little improvement. Now sending data and commands is a little bit faster. This is my GPIO write function edit:

``` swift

private func writeToFile(path: String, value:String){

        let fp: UnsafeMutablePointer<FILE>

        if let _fp = writeFileDescriptors[path] {
            fp = _fp
        } else {
            fp = fopen(path,"w")
            writeFileDescriptors[path] = fp
        }

        if fp != nil {
            let ret = fwrite(value, strideof(CChar), value.characters.count, fp)
            if ret<value.characters.count {
                if ferror(fp) != 0 {
                    perror("Error while writing to file")
                    abort()
                }
            }
            rewind(fp)
        }
    }
```

Where writeFileDescriptors is a GPIO's property defined as:

``` swift
private var writeFileDescriptors = [String : UnsafeMutablePointer<FILE>]()
```

![better](https://cloud.githubusercontent.com/assets/1050414/13027597/26bb1e14-d255-11e5-9adc-d24d09163918.gif)

**Comment by uraimo** [comment]
Yes, that's exactly what i tried a few weeks ago, still not fast enough, but comparable in my experience with what you get with the Pi 5110 C library, that uses a bit banging SPI too.

So, i did some tests and modified the original VirtualSPI [here](https://github.com/uraimo/SwiftyGPIO/commit/bb12bfc8eb364b0ebe3dbb91068b4eb215b75752), it's essentially the same thing you did but all in sendData.

From what i've seen testing on a CHIP this version is slightly faster than the 5110 C library (that doesn't caches the file pointers), and now the only thing that matters is the number of file syscalls performed, if those are not reduced in number every other "optimization" is irrelevant.

To have something faster we need [#9](https://github.com/uraimo/SwiftyGPIO/issues/9), i don't see other alternatives.

Just for reference, on a CHIP, as it was before we were able to generate a 1.5Khz pulse, while now we are around 3.5Khz, a big improvement but still slow :)

**Comment by uraimo** [comment]
Ok, i've removed buffering entirely and we should be around 4Khz now... :)

You can open a PR on SwiftyGPIO for your gpio object improvement if you want/have time, just replace rewind with fflush.

**Comment by uraimo** [comment]
Ok, since i was already playing with it i've started experimenting with memory mapped gpios, now on a RaspberryPi 2 i can generate a ~~7Mhz~~12Mhz impulse, a ~~1500~~3000-fold increase :)

Now i just have to integrate everything in SwiftyGPIO, and introduce a delay because we are now too fast for the LCD :smile:

**Comment by eugeniobaglieri** [comment]
Good!!! I've read something about mmapped gpio, i would like extend SwiftyGPIO whit this, but i don't have the required knowledge to write this code. 
PS: How do you measure max freq.?
PS2: I read your VisrtualSPI's send data. I'm not sure but i think that could be a conflict between your new implementation and my improvement, we have two filePointer to the same file opened with write permission.

**Comment by uraimo** [comment]
1) I could have checked every n (e.g. 1k) cycles or so that 1 second or more was elapsed and then do a division, but i just did a few million iterations until i saw that i needed 1 second more or less to output the transitions :)
2) Oh right, and i don't plan to manage concurrent access conditions...

I put a sample in a gist that you can check out [here](https://gist.github.com/uraimo/a6799be9c1e1e8ac3ed5)

**Comment by uraimo** [comment]
Uhm, it looks like that with all the swift code around the sending of bits a clock delay it's not needed.
You just have to update SwiftyGPIO and change the enum you use in your application to get the pins with the new one:

``` swift
let gpios = SwiftyGPIO.getGPIOsForBoard(.RaspberryPi2)
```

And you should be good to go without further modifications (the 5110 lib didn't change).

I've tested it on a RaspberryPi 2 and it draws instantly (maybe it's just slightly too fast), it should have the same performance on other raspberries too.

**Comment by uraimo** [comment]
I'm closing this since now it's quite fast :)
